const SUBJECTS_IN_EXAM = {
  MATH: 'Toán',
  ENGLISH: 'Tiếng anh',
  PHYSICS: 'Vật lý',
  CHEMISTRY: 'Hóa học',
  BIOLOGY: 'Sinh học',
  HISTORY: 'Lịch sử',
  GEOGRAPHY: 'Địa lý',
};

const QUESTION_TYPES = {
  MULTIPLE_CHOICE: 'Trắc nghiệm',
  TRUE_FALSE: 'Đúng/Sai',
  SHORT_ANSWER: 'Tự luận',
};

const NUMBER_OF_QUESTIONS_BY_SUBJECT = {
  [SUBJECTS_IN_EXAM.MATH]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 12,
    [QUESTION_TYPES.TRUE_FALSE]: 4,
    [QUESTION_TYPES.SHORT_ANSWER]: 6,
  },
  [SUBJECTS_IN_EXAM.ENGLISH]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 40,
  },
  [SUBJECTS_IN_EXAM.PHYSICS]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 18,
    [QUESTION_TYPES.TRUE_FALSE]: 4,
    [QUESTION_TYPES.SHORT_ANSWER]: 6,
  },
  [SUBJECTS_IN_EXAM.CHEMISTRY]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 18,
    [QUESTION_TYPES.TRUE_FALSE]: 4,
    [QUESTION_TYPES.SHORT_ANSWER]: 6,
  },
  [SUBJECTS_IN_EXAM.BIOLOGY]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 18,
    [QUESTION_TYPES.TRUE_FALSE]: 4,
    [QUESTION_TYPES.SHORT_ANSWER]: 6,
  },
  [SUBJECTS_IN_EXAM.HISTORY]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 24,
    [QUESTION_TYPES.TRUE_FALSE]: 4,
  },
  [SUBJECTS_IN_EXAM.GEOGRAPHY]: {
    [QUESTION_TYPES.MULTIPLE_CHOICE]: 18,
    [QUESTION_TYPES.TRUE_FALSE]: 4,
    [QUESTION_TYPES.SHORT_ANSWER]: 6,
  },
};

export { SUBJECTS_IN_EXAM, QUESTION_TYPES, NUMBER_OF_QUESTIONS_BY_SUBJECT };
