from enum import StrEnum


class UserCodes(StrEnum):
    ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_TOKEN = "INVALID_TOKEN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_USER_ID = "INVALID_USER_ID"


class UserSessionCodes(StrEnum):
    USER_SESSION_NOT_FOUND = "USER_SESSION_NOT_FOUND"


class QuestionCodes(StrEnum):
    NOT_FOUND = "QUESTION_NOT_FOUND"
    ALREADY_EXISTS = "QUESTION_ALREADY_EXISTS"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_QUESTION_ID = "INVALID_QUESTION_ID"
